import {
  CalendarIcon,
  EnvelopeIcon,
  CalendarClockIcon,
  CombinedFormIcon,
  ClassicScheduleIcon,
  SimulationIcon,
} from "../shared/icons";

const EXPERIENCES = [
  {
    id: "host-scheduling",
    title: "Host Scheduling Form",
    pitchTitle: "Create a Gathering",
    description: "Create and configure a group gathering with smart multi-dimensional scheduling across people, times, and places.",
    pitchDescription: "Configure dates, locations, and preferences for a new group event.",
    app: "quorum",
    icon: CalendarIcon,
    status: "active",
    persona: "host",
    category: "demo",
    load: () => import("./scheduling/HostSchedulingForm.jsx"),
  },
  {
    id: "invitee-response",
    title: "Invitee Response",
    pitchTitle: "Respond to an Invite",
    description: "Respond to a gathering invite by ranking your top preferences and marking times you're unavailable.",
    pitchDescription: "Rank your preferred times and locations from available options.",
    app: "quorum",
    icon: EnvelopeIcon,
    status: "active",
    persona: "invitee",
    category: "demo",
    load: () => import("./scheduling/InviteeExperience.jsx"),
  },
  {
    id: "invitee-calendar",
    title: "Invitee Calendar View",
    pitchTitle: "Calendar Response",
    description: "Respond to a gathering invite using an interactive calendar that shows available days and lets you pick specific time slots.",
    pitchDescription: "Pick your availability using an interactive calendar overlay.",
    app: "quorum",
    icon: CalendarClockIcon,
    status: "active",
    persona: "invitee",
    category: "demo",
    load: () => import("./scheduling/InviteeCalendarExperience.jsx"),
  },
  {
    id: "host-combined",
    title: "Host Combined Form",
    pitchTitle: "Quick Setup",
    description: "Create a gathering with schedule, location, and commute buffer combined into a single streamlined step.",
    pitchDescription: "Streamlined single-step gathering creation with all options at once.",
    app: "quorum",
    icon: CombinedFormIcon,
    status: "active",
    persona: "host",
    category: "demo",
    load: () => import("./scheduling/HostCombinedForm.jsx"),
  },
  {
    id: "host-classic",
    title: "Host Classic Scheduling",
    pitchTitle: "Calendar-Based Setup",
    description: "Classic mode scheduling with specific meeting times, calendar availability, location selection, and host preference ranking.",
    pitchDescription: "Create a gathering using specific time slots and calendar availability.",
    app: "quorum",
    icon: ClassicScheduleIcon,
    status: "active",
    persona: "host",
    category: "demo",
    load: () => import("./scheduling/HostClassicScheduling.jsx"),
  },
  {
    id: "s01-simulation",
    title: "S-01: Scenario Simulation",
    pitchTitle: "Community Planning Session",
    description: "End-to-end simulation of a single host, single gathering with 12 invitees — watch quorum reached in real time.",
    pitchDescription: "Watch a full scheduling scenario play out — from invites to quorum to confirmation.",
    app: "quorum",
    icon: SimulationIcon,
    status: "active",
    persona: null,
    category: "scenario",
    load: () => import("./scheduling/S01Simulation.jsx"),
  },
];

export const APPS = [
  {
    id: "quorum",
    name: "Quorum",
    tagline: "Smart group scheduling",
    description: "Organize gatherings with quorum-based confirmation, location matching, and overflow support.",
    icon: CalendarClockIcon,
    status: "active",
  },
  {
    id: "trellis",
    name: "Trellis",
    tagline: "Content discovery",
    description: "Surface and share interesting content with your community.",
    icon: null,
    status: "coming_soon",
  },
];

export default EXPERIENCES;
